migrate(
  (app) => {
    const colMembros = app.findCollectionByNameOrId('membros')

    // 51 novos registros correspondentes à lista 49..100 (deslocamento +2 -> banco 51..102)
    // Fichas 49 e 50 pré-existentes no banco NÃO são tocadas.
    const novosMembros = [
      // Nº 49 -> BANCO 51
      {
        numero_ficha: '51',
        nome: 'Valderlanio Carneiro Araújo',
        filiacao: 'Benedito Frota Araújo e Francisca Carneiro de Araújo',
        data_nascimento_iso: '1984-10-10 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – Ce',
        estado_civil: 'Casado',
        rg: '2002031027463',
        cpf: '008.723.553-65',
        data_conversao_iso: '',
        data_conversao_texto: '23/11/2007 Aprox.',
        data_batismo_iso: '1998-04-16 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Raimundo Fontele Gomes',
        observacao: 'Função: Presbítero',
      },
      // Nº 50 -> BANCO 52
      {
        numero_ficha: '52',
        nome: 'Joana Freire Carneiro',
        filiacao: 'Francisco Eudes Freire e Maria das Graças Freire',
        data_nascimento_iso: '1984-07-03 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo - Ce',
        estado_civil: 'Casada',
        rg: '2001031038963',
        cpf: '003.178.653-74',
        data_conversao_iso: '2014-10-25 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2015-07-11 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Raimundo Fontele Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 51 -> BANCO 53
      {
        numero_ficha: '53',
        nome: 'Benedito Frota Araújo',
        filiacao: 'Antônio José de Araújo e Lídia Frota Vasconcelos',
        data_nascimento_iso: '1947-06-17 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Tianguá – Ce',
        estado_civil: 'Casado',
        rg: '1218568',
        cpf: '033.716.623-49',
        data_conversao_iso: '',
        data_conversao_texto: '05/1983',
        data_batismo_iso: '1984-02-20 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Sitio Canta galo',
        observacao: 'Função: Diácono',
      },
      // Nº 52 -> BANCO 54
      {
        numero_ficha: '54',
        nome: 'Francisca Dalva Araújo de Lima',
        filiacao: 'Vicente de Paula de Araújo e Izaura Frota de Araújo',
        data_nascimento_iso: '1952-06-15 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Tianguá – Ce',
        estado_civil: 'Casada',
        rg: '00000',
        cpf: '313.855.163-72',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '1972-09-07 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Sitio Canta galo',
        observacao: 'Função: Membro',
      },
      // Nº 53 -> BANCO 55
      {
        numero_ficha: '55',
        nome: 'Clécio Araújo de Lima',
        filiacao: 'Francisco Nunes de Lima e Francisca Dalva Araújo de Lima',
        data_nascimento_iso: '1975-11-25 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Fortaleza – Ce',
        estado_civil: 'Casado',
        rg: '00000',
        cpf: '570.338.892-91',
        data_conversao_iso: '2017-10-12 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2018-07-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Sitio Canta galo',
        observacao: 'Função: Auxiliar',
      },
      // Nº 54 -> BANCO 56
      {
        numero_ficha: '56',
        nome: 'Antônia Paulo Fontenele de Lima',
        filiacao: 'Francisco Sampaio Fontenele e Antônia Paulo Fontenele',
        data_nascimento_iso: '1985-02-01 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '00000',
        cpf: '017.190.983-60',
        data_conversao_iso: '2017-08-27 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Sitio Canta galo',
        observacao: 'Função: Membro',
      },
      // Nº 55 -> BANCO 57
      {
        numero_ficha: '57',
        nome: 'Clesia Araújo de Lima',
        filiacao: 'Francisco Nunes de Lima e Francisca Dalva Araújo de Lima',
        data_nascimento_iso: '1976-11-05 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Camocim – Ce',
        estado_civil: 'Casada',
        rg: '2743675-94',
        cpf: '731.495.783-53',
        data_conversao_iso: '2017-09-27 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2021-10-03 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Sitio Canta galo',
        observacao: 'Função: Membro',
      },
      // Nº 56 -> BANCO 58
      {
        numero_ficha: '58',
        nome: 'Andreia Guilherme Bezerra',
        filiacao: 'João Cordeiro Bezerra e Maria Gomes Pereira',
        data_nascimento_iso: '1989-05-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Granja – Ce',
        estado_civil: 'Casada',
        rg: '20070729934',
        cpf: '018.060.053-28',
        data_conversao_iso: '',
        data_conversao_texto: '00/00/2000',
        data_batismo_iso: '2018-07-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Sitio Canta galo',
        observacao: 'Função: Membro',
      },
      // Nº 57 -> BANCO 59
      {
        numero_ficha: '59',
        nome: 'Eliana Cardoso Nascimento',
        filiacao: 'Salvandir Pereira do Nascimento e Raimunda Cardoso do Nascimento',
        data_nascimento_iso: '1962-12-06 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Manaus – Am',
        estado_civil: 'Casada',
        rg: '20070729934',
        cpf: '142.716.482-72',
        data_conversao_iso: '',
        data_conversao_texto: '00/00/0000',
        data_batismo_iso: '2018-07-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Sitio Canta galo',
        observacao: 'Função: Membro',
      },
      // Nº 58 -> BANCO 60
      {
        numero_ficha: '60',
        nome: 'José Alves Ferreira',
        filiacao: 'Leocádio Alves Ferreira e Vicença Gomes de Carvalho',
        data_nascimento_iso: '1949-06-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casado',
        rg: '2007273846-9',
        cpf: '710648183-15',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '1990-02-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinhas',
        observacao: 'Função: Diácono',
      },
      // Nº 59 -> BANCO 61
      {
        numero_ficha: '61',
        nome: 'Raimunda Ferreira de Carvalho',
        filiacao: 'José Ferreira de Carvalho e Mariana Cézar de Carvalho',
        data_nascimento_iso: '1957-06-06 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '3089959-96',
        cpf: '978.871.103-00',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '',
        data_batismo_texto: '15/08/1990 Aprox.',
        endereco: 'Casinhas',
        observacao: '',
      },
      // Nº 60 -> BANCO 62
      {
        numero_ficha: '62',
        nome: 'Jonas de Carvalho Ferreira',
        filiacao: 'José Alves Ferreira e Raimunda Ferreira de Carvalho',
        data_nascimento_iso: '1996-07-23 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Solteiro',
        rg: '2007862820-7',
        cpf: '607.712.413-30',
        data_conversao_iso: '',
        data_conversao_texto: 'Na fé',
        data_batismo_iso: '2010-01-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinhas',
        observacao: '',
      },
      // Nº 61 -> BANCO 63
      {
        numero_ficha: '63',
        nome: 'Francisco Carvalho Ferreira',
        filiacao: 'José Alves Ferreira e Raimunda Ferreira de Carvalho',
        data_nascimento_iso: '1982-01-18 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casado',
        rg: '98031064710',
        cpf: '000.263.903-37',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '1996-12-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinhas',
        observacao: 'Função: Auxiliar',
      },
      // Nº 62 -> BANCO 64
      {
        numero_ficha: '64',
        nome: 'Rita Araújo Ferreira',
        filiacao: 'Antônio Pereira de Vasconcelos e Antônia Barboza de Araújo',
        data_nascimento_iso: '1993-11-16 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Tianguá – Ce',
        estado_civil: 'Casada',
        rg: '',
        cpf: '069.105.243-30',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2013-03-29 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinhas',
        observacao: 'Função: Membro',
      },
      // Nº 63 -> BANCO 65
      {
        numero_ficha: '65',
        nome: 'Maria Ferreira Dourado',
        filiacao: 'Leocádio Alves Ferreira e Vicença Gomes de Carvalho',
        data_nascimento_iso: '1944-12-18 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Viúva',
        rg: '2019089408-8',
        cpf: '701.581.263-00',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2020-11-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinhas',
        observacao: 'Função: Membro',
      },
      // Nº 64 -> BANCO 66
      {
        numero_ficha: '66',
        nome: 'Adélia Fontenele Cardoso',
        filiacao: 'Manoel Chaves Cardoso e Maria Stela Fontenele Cardoso',
        data_nascimento_iso: '1981-01-01 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '34881088-2000',
        cpf: '039.847193-29',
        data_conversao_iso: '',
        data_conversao_texto: 'Na fé',
        data_batismo_iso: '1994-07-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'João Batista de Vasconcelos',
        observacao: 'Função: Membro',
      },
      // Nº 65 -> BANCO 67
      {
        numero_ficha: '67',
        nome: 'Débora Cardoso do Nascimento',
        filiacao: 'Aristides do Nascimento e Adélia Fontenele Cardoso',
        data_nascimento_iso: '2009-01-24 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – Ce',
        estado_civil: 'Solteira',
        rg: '',
        cpf: '049.737.292-48',
        data_conversao_iso: '',
        data_conversao_texto: 'Na fé',
        data_batismo_iso: '2021-10-03 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'João Batista de Vasconcelos',
        observacao: 'Função: Membro',
      },
      // Nº 66 -> BANCO 68
      {
        numero_ficha: '68',
        nome: 'Raimunda Alves Cardozo',
        filiacao: 'Gerardo Alves Fonseca e Francisca Alves Fontenele',
        data_nascimento_iso: '1974-01-02 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '3065774-96',
        cpf: '981.930.073-87',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '',
        data_batismo_texto: '26/02/1987 Aprox.',
        endereco: 'Rua Antônio Ferreira Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 67 -> BANCO 69
      {
        numero_ficha: '69',
        nome: 'Jacinara Alves Cardoso',
        filiacao: 'Antônio Fontenele Cardoso e Raimunda Alves Cardoso',
        data_nascimento_iso: '2006-04-05 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – Ce',
        estado_civil: 'Solteira',
        rg: 'Não tem',
        cpf: '636.730.903-99',
        data_conversao_iso: '',
        data_conversao_texto: 'Na fé',
        data_batismo_iso: '2020-11-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Antônio Ferreira Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 68 -> BANCO 70
      {
        numero_ficha: '70',
        nome: 'Nair Alves Cardoso de Sousa',
        filiacao: 'Antônio Fontenele Cardoso e Raimunda Alves Cardoso',
        data_nascimento_iso: '1995-04-10 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – Ce',
        estado_civil: 'Casada',
        rg: '',
        cpf: '070.687.083-23',
        data_conversao_iso: '',
        data_conversao_texto: 'Na fé',
        data_batismo_iso: '2008-10-31 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Antônio Ferreira Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 69 -> BANCO 71
      {
        numero_ficha: '71',
        nome: 'Fábio da Silva Alves',
        filiacao: 'Raimundo Alves da Silva e Maria do Socorro da Silva',
        data_nascimento_iso: '1986-08-27 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – Ce',
        estado_civil: 'Casado',
        rg: '',
        cpf: '021.137.923-97',
        data_conversao_iso: '2017-08-27 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Raimundo Fonteles Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 70 -> BANCO 72
      {
        numero_ficha: '72',
        nome: 'Maria de Fátima Dias',
        filiacao: 'Vicente Rodrigues Dias e Antônia Lopes de Sousa',
        data_nascimento_iso: '1987-08-29 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '2004019055874',
        cpf: '037.167.373-99',
        data_conversao_iso: '2005-09-06 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2006-10-06 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Raimundo Fonteles Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 71 -> BANCO 73
      {
        numero_ficha: '73',
        nome: 'Francisca das Chagas de Matos (Chaguinha Flor)',
        filiacao: 'Raimundo Alves de Matos e Lucinda Henrique Barbosa',
        data_nascimento_iso: '1948-07-25 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Viúva',
        rg: '2003005110314',
        cpf: '949.558.833-20',
        data_conversao_iso: '2013-06-21 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2014-07-06 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. Alberto Batista Fontenele',
        observacao: '',
      },
      // Nº 72 -> BANCO 74
      {
        numero_ficha: '74',
        nome: 'Lucinete Pereira de Matos',
        filiacao: 'José Pereira de Matos e Francisca das Chagas de Matos',
        data_nascimento_iso: '1969-12-13 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '2004005019943',
        cpf: '002.426.223-48',
        data_conversao_iso: '2007-05-10 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2007-10-31 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Trav. Raimundo Ferreira Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 73 -> BANCO 75
      {
        numero_ficha: '75',
        nome: 'Raiane Matos de Arruda',
        filiacao: 'Valdivan Felix de Arruda e Maria Valda de Matos',
        data_nascimento_iso: '1998-08-08 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '',
        cpf: '075.985.523-47',
        data_conversao_iso: '2016-07-15 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2018-07-20 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // Nº 74 -> BANCO 76
      {
        numero_ficha: '76',
        nome: 'Antônio Vieira Sampaio',
        filiacao: 'Terezinha Vieira Sampaio',
        data_nascimento_iso: '1995-02-03 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – Ce',
        estado_civil: 'Casado',
        rg: '',
        cpf: '063.902.243-03',
        data_conversao_iso: '2016-07-15 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2018-07-20 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // Nº 75 -> BANCO 77
      {
        numero_ficha: '77',
        nome: 'Charles de Matos Arruda',
        filiacao: 'Valdivan Félix de Arruda e Maria Valda de Matos',
        data_nascimento_iso: '1995-08-18 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral-Ce',
        estado_civil: 'Casado',
        rg: '2008362182-7',
        cpf: '607.707.683-00',
        data_conversao_iso: '',
        data_conversao_texto: '12/07/2012 aprox.',
        data_batismo_iso: '2015-07-11 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Diácono',
      },
      // Nº 76 -> BANCO 78
      {
        numero_ficha: '78',
        nome: 'Naiane Costa do Nascimento',
        filiacao: 'Francisco Raimundo do Nascimento e Maria Júlia Costa do Nascimento',
        data_nascimento_iso: '1996-02-22 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – Ce',
        estado_civil: 'Casada',
        rg: '',
        cpf: '068.234.723-08',
        data_conversao_iso: '2005-08-03 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2007-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua José Batista Fontenele',
        observacao: 'Função: Membro',
      },
      // Nº 77 -> BANCO 79
      {
        numero_ficha: '79',
        nome: 'José Fernandes Tavares',
        filiacao: 'João Cordeiro Tavares e Maria Fernandes Tavares',
        data_nascimento_iso: '1940-08-29 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Viçosa do Ceará – Ce',
        estado_civil: 'Casado',
        rg: '94008015579',
        cpf: '013.991.523-00',
        data_conversao_iso: '',
        data_conversao_texto: '000000000',
        data_batismo_iso: '',
        data_batismo_texto: '1999',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // Nº 78 -> BANCO 80
      {
        numero_ficha: '80',
        nome: 'Vera Lucia Veras Tavares',
        filiacao: 'João Marques Veras e Raimunda Fernandes Veras',
        data_nascimento_iso: '1945-01-25 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Granja – Ce',
        estado_civil: 'Casada',
        rg: '2009051580-80',
        cpf: '228.952.303-82',
        data_conversao_iso: '',
        data_conversao_texto: 'não lembra',
        data_batismo_iso: '',
        data_batismo_texto: '1999',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // Nº 79 -> BANCO 81
      {
        numero_ficha: '81',
        nome: 'Nadir Ferreira Monteiro',
        filiacao: 'José Monteiro e Madalena Ferreira Monteiro',
        data_nascimento_iso: '1963-12-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Maracanã – Pa',
        estado_civil: 'Casado',
        rg: '1627980',
        cpf: '293.779.002-04',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '1987-12-15 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Diácono',
      },
      // Nº 80 -> BANCO 82
      {
        numero_ficha: '82',
        nome: 'Maria de Fátima da Rocha Monteiro',
        filiacao: 'Antônio Francisco da Rocha e Maria Ferreira Lima da Rocha',
        data_nascimento_iso: '1957-02-08 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Belém – Pa',
        estado_civil: 'Casada',
        rg: '3674380',
        cpf: '117.569.262-04',
        data_conversao_iso: '',
        data_conversao_texto: '06/1968',
        data_batismo_iso: '1968-12-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // Nº 81 -> BANCO 83
      {
        numero_ficha: '83',
        nome: 'Antonio de Vasconcelos',
        filiacao: 'Raimundo Fonteles de Arruda e Maria José de Vasconcelos',
        data_nascimento_iso: '1973-10-01 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Brejo de Areia - Ma',
        estado_civil: 'Casado',
        rg: '2571079',
        cpf: '474.935.343-49',
        data_conversao_iso: '',
        data_conversao_texto: '10/07/1991 Ap.',
        data_batismo_iso: '1993-06-26 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. João Belchior 399',
        observacao: 'Função: Diácono',
      },
      // Nº 82 -> BANCO 84
      {
        numero_ficha: '84',
        nome: 'Maria Aparecida Eugênio',
        filiacao: 'José Eugênio Tomaz e Maria Marques Vitorino',
        data_nascimento_iso: '1965-04-18 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Solteira',
        rg: '1013608-86',
        cpf: '065.456.283-05',
        data_conversao_iso: '1996-04-20 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '1996-04-24 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // Nº 83 -> BANCO 85
      {
        numero_ficha: '85',
        nome: 'Ana Letícia de Almeida Rodrigues',
        filiacao: 'Raimundo Nonato Rodrigues e Maria Aura Almeida',
        data_nascimento_iso: '1997-02-14 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Solteira',
        rg: '',
        cpf: '075.985.313-40',
        data_conversao_iso: '2016-12-16 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-07-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // Nº 84 -> BANCO 86
      {
        numero_ficha: '86',
        nome: 'Maria das Graças Chaves Silveira',
        filiacao: 'Francisco Fernandes Chaves e Elisa Florêncio Batista',
        data_nascimento_iso: '1955-01-10 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Coreaú – Ce',
        estado_civil: 'Viúva',
        rg: '1178270-86',
        cpf: '024.564.713-93',
        data_conversao_iso: '2011-07-08 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '1990-10-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // Nº 85 -> BANCO 87
      {
        numero_ficha: '87',
        nome: 'Antônia Anésia Chaves',
        filiacao: 'Francisco Fernandes Chaves e Elisa Florêncio Chaves',
        data_nascimento_iso: '1960-07-30 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Viúva',
        rg: '507128-82',
        cpf: '506.628.053-72',
        data_conversao_iso: '2004-05-01 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2005-03-19 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Trav.; João Batista de Vasconcelos/Dora',
        observacao: 'Função: Membro',
      },
      // Nº 86 -> BANCO 88
      {
        numero_ficha: '88',
        nome: 'Antônio Mauro de Oliveira',
        filiacao: 'Francisco Mauro de Oliveira e Antônia Sampaio de Oliveira',
        data_nascimento_iso: '1982-10-25 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca-Ce',
        estado_civil: 'Casado',
        rg: '3461421-2000',
        cpf: '007.706.623-58',
        data_conversao_iso: '1998-10-24 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '1999-05-15 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: '',
        observacao: 'Função: Auxiliar',
      },
      // Nº 87 -> BANCO 89
      {
        numero_ficha: '89',
        nome: 'Natália Martins de Vasconcelos Oliveira',
        filiacao: 'José Pereira de Vasconcelos e Maria da Conceição Martins',
        data_nascimento_iso: '1993-01-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Camocim-Ce',
        estado_civil: 'Casada',
        rg: 'Não tem',
        cpf: '059.789.603-80',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2005-12-31 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // Nº 88 -> BANCO 90
      {
        numero_ficha: '90',
        nome: 'Raimundo Nonato Moura da Costa',
        filiacao: 'Manoel Jerônimo da Costa e Maria do Socorro da Costa',
        data_nascimento_iso: '1970-05-15 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Granja-Ce',
        estado_civil: 'Casado',
        rg: '',
        cpf: '000.127.813-47',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2017-01-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Raimundo Fontele Gomes',
        observacao: 'Função: Auxiliar',
      },
      // Nº 89 -> BANCO 91
      {
        numero_ficha: '91',
        nome: 'Lucilene de Sousa Oliveira Costa',
        filiacao: 'Vicente Pereira de Sousa e Eugênia Nonata de Oliveira',
        data_nascimento_iso: '1975-11-05 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Granja-Ce',
        estado_civil: 'Casada',
        rg: '',
        cpf: '978.932.773-00',
        data_conversao_iso: '2016-07-27 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-01-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Raimundo Fontenele Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 90 -> BANCO 92
      {
        numero_ficha: '92',
        nome: 'Antônia Natália da Costa Sousa',
        filiacao: 'Raimundo Nonato Moura da Costa e Lucilene de Sousa Oliveira Costa',
        data_nascimento_iso: '1993-10-30 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Granja-Ce',
        estado_civil: 'Solteira',
        rg: '',
        cpf: '063.212.313-39',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2017-01-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Raimundo Fontenele Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 91 -> BANCO 93
      {
        numero_ficha: '93',
        nome: 'Francisco da Costa Sousa',
        filiacao: 'Raimundo Nonato Moura da Costa e Lucilene de Sousa Oliveira Costa',
        data_nascimento_iso: '1997-01-31 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Granja-Ce',
        estado_civil: 'Solteiro',
        rg: '',
        cpf: '022.502.263-00',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2017-01-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Raimundo Fontenele Gomes',
        observacao: 'Função: Membro',
      },
      // Nº 92 -> BANCO 94
      {
        numero_ficha: '94',
        nome: 'Maciel da Costa Sousa',
        filiacao: 'Raimundo Nonato Moura da Costa e Lucilene de Sousa Oliveira Costa',
        data_nascimento_iso: '1998-10-31 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Granja-Ce',
        estado_civil: 'Casado',
        rg: '',
        cpf: '078.981.993-75',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2017-01-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua José Cristino da Costa',
        observacao: 'Função: Membro',
      },
      // Nº 93 -> BANCO 95
      {
        numero_ficha: '95',
        nome: 'Antônia Machado dos Santos',
        filiacao: 'Anísio Machado Tiago e Raimunda Borges dos Santos',
        data_nascimento_iso: '1999-11-03 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca-Ce',
        estado_civil: 'Casada',
        rg: '',
        cpf: '074.460.033-24',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2014-07-06 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua José Cristino da Costa',
        observacao: 'Função: Membro',
      },
      // Nº 94 -> BANCO 96
      {
        numero_ficha: '96',
        nome: 'Raimunda Borges dos Santos',
        filiacao: 'Mansueta Borges Leopoldo e Expedita Martins dos Santos',
        data_nascimento_iso: '1954-02-28 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca-Ce',
        estado_civil: 'Viúva',
        rg: '',
        cpf: '907.822.083-04',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2014-07-06 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua José Cristino da Costa',
        observacao: 'Função: Membro',
      },
      // Nº 95 -> BANCO 97
      {
        numero_ficha: '97',
        nome: 'José Rodrigo Frota',
        filiacao: 'Francisco Moreira Frota e Maria da Conceição Vasconcelos',
        data_nascimento_iso: '1982-12-23 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo-Ce',
        estado_civil: 'Casado',
        rg: '99031067467',
        cpf: '917.570.103-00',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2009-09-17 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Raimundo Benício de Vasconcelos',
        observacao: 'Função: Diácono',
      },
      // Nº 96 -> BANCO 98
      {
        numero_ficha: '98',
        nome: 'Jaqueline Fernandes Cavalcante Frota',
        filiacao: 'Antônio Fernandes Cavalcante e Maria das Graças Pessoa',
        data_nascimento_iso: '1990-03-01 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca-Ce',
        estado_civil: 'Casada',
        rg: '2006015141306',
        cpf: '054.926.083-80',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2009-09-17 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Raimundo Benício de Vasconcelos',
        observacao: 'Função: Membro',
      },
      // Nº 97 -> BANCO 99
      {
        numero_ficha: '99',
        nome: 'Belchior Fernandes de Vasconcelos',
        filiacao: 'Francisco Fernandes Lima e Maria Secundo de Vasconcelos',
        data_nascimento_iso: '1952-10-08 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casado',
        rg: '1.272.547',
        cpf: '865.509.933-34',
        data_conversao_iso: '1986-06-22 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '1987-12-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Francisco Gualberto da Cunha',
        observacao: 'Função: Diácono',
      },
      // Nº 98 -> BANCO 100
      {
        numero_ficha: '100',
        nome: 'Ernestina Moreira Vasconcelos',
        filiacao: 'Francisco Moacir da Costa e Francisca das Chagas Costa',
        data_nascimento_iso: '1964-01-20 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '507188-82',
        cpf: '978.078.693-72',
        data_conversao_iso: '1987-08-06 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '1987-12-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Francisco Gualberto da Cunha',
        observacao: 'Função: Membro',
      },
      // Nº 99 -> BANCO 101
      {
        numero_ficha: '101',
        nome: 'Maria Mônica Moreira de Vasconcelos',
        filiacao: 'Belchior Fernandes de Vasconcelos e Ernestina Moreira Vasconcelos',
        data_nascimento_iso: '1985-11-17 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Divorciada',
        rg: '2004015069820',
        cpf: '030.587.323-76',
        data_conversao_iso: '',
        data_conversao_texto: 'Na fé',
        data_batismo_iso: '2000-12-22 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Francisco Gualberto da Cunha',
        observacao: 'Função: Membro',
      },
      // Nº 100 -> BANCO 102
      {
        numero_ficha: '102',
        nome: 'Francisca das Chagas Silva Matos',
        filiacao: 'Raimundo Carlos da Silva e Maria Conceição Silva',
        data_nascimento_iso: '1964-02-12 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca - Ce',
        estado_civil: 'Casada',
        rg: '2365431-92',
        cpf: '993.612.563-00',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2006-07-22 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua José Batista Fontenele',
        observacao: 'Função: Membro',
      },
    ]

    for (const m of novosMembros) {
      let record
      // Idempotência: buscar por numero_ficha antes de criar
      try {
        record = app.findFirstRecordByData('membros', 'numero_ficha', m.numero_ficha)
      } catch (_) {
        record = new Record(colMembros)
      }

      record.set('numero_ficha', m.numero_ficha)
      record.set('nome', m.nome)
      record.set('filiacao', m.filiacao)
      record.set('naturalidade', m.naturalidade)
      record.set('estado_civil', m.estado_civil)
      record.set('rg', m.rg)
      record.set('cpf', m.cpf)
      record.set('endereco', m.endereco)
      record.set('observacao', m.observacao)
      record.set('congregacao', 'Sede')
      record.set('status', 'Ativo')

      if (m.data_nascimento_iso) {
        record.set('data_nascimento', m.data_nascimento_iso)
      } else {
        record.set('data_nascimento', null)
      }
      record.set('data_nascimento_texto', m.data_nascimento_texto)

      if (m.data_conversao_iso) {
        record.set('data_conversao', m.data_conversao_iso)
      } else {
        record.set('data_conversao', null)
      }
      record.set('data_conversao_texto', m.data_conversao_texto)

      if (m.data_batismo_iso) {
        record.set('data_batismo', m.data_batismo_iso)
      } else {
        record.set('data_batismo', null)
      }
      record.set('data_batismo_texto', m.data_batismo_texto)

      app.save(record)
    }
  },
  (app) => {
    // Reverter os 51 novos cadastros (fichas 51 a 102)
    for (let f = 51; f <= 102; f++) {
      try {
        const record = app.findFirstRecordByData('membros', 'numero_ficha', String(f))
        app.delete(record)
      } catch (_) {}
    }
  },
)
