migrate(
  (app) => {
    const colMembros = app.findCollectionByNameOrId('membros')

    // 72 registros principais (fichas 103 a 174, sem ficha 136; Ernanda Fontenele Sampaio na 137)
    // + 2 registros especiais (ficha 1 e ficha 7)
    // Total de 74 registros a processar
    const membrosNovos = [
      // MEMBRO Nº 103
      {
        numero_ficha: '103',
        nome: 'Maria Lindalva Vasconcelos Batista',
        filiacao: 'Francisco Vasconcelos Batista e Raimunda Jacinto de Vasconcelos',
        data_nascimento_iso: '1974-10-17 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '2365728-92',
        cpf: '841.906.042-91',
        data_conversao_iso: '',
        data_conversao_texto: '15/11/1999 Ap.',
        data_batismo_iso: '2011-01-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. João Belchior 399',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 104
      {
        numero_ficha: '104',
        nome: 'Ana Alice Batista Vasconcelos',
        filiacao: 'Antonio de Vasconcelos e Maria Lindalva Vasconcelos Batista',
        data_nascimento_iso: '2004-05-11 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Solteira',
        rg: '2008864200-8',
        cpf: '102.194.233-26',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2020-11-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. João Belchior 399',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 105
      {
        numero_ficha: '105',
        nome: 'Tainara Batista Vasconcelos',
        filiacao: 'Antonio de Vasconcelos e Maria Lindalva Vasconcelos Batista',
        data_nascimento_iso: '2005-09-18 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – Ce',
        estado_civil: 'Solteira',
        rg: '2008864195-8',
        cpf: '116.331.263-07',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2020-11-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. João Belchior 399',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 106
      {
        numero_ficha: '106',
        nome: 'João Paulo Ferreira Dourado',
        filiacao: 'Zacarias Pereira Dourado e Maria Ferreira Dourado',
        data_nascimento_iso: '1983-04-24 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Casado',
        rg: '98028109580',
        cpf: '993.567.833-49',
        data_conversao_iso: '1999-03-13 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '1999-05-15 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. João Batista Vasconcelos',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 107
      {
        numero_ficha: '107',
        nome: 'Edmaura Pereira Rodrigues Dourado',
        filiacao: 'Edivaldo Pereira Rodrigues e Sebastiana Sampaio Rodrigues',
        data_nascimento_iso: '1987-04-30 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – CE',
        estado_civil: 'Casada',
        rg: '',
        cpf: '035.440.533-06',
        data_conversao_iso: '',
        data_conversao_texto: '00/00/0000',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. João Batista Vasconcelos',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 108
      {
        numero_ficha: '108',
        nome: 'Maria Jocelina da Silva',
        filiacao: 'Raimundo Alves da Silva e Maria do Socorro da Silva',
        data_nascimento_iso: '1967-03-01 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Martinópole – Ce',
        estado_civil: 'Casada',
        rg: '2858324 - 94',
        cpf: '978.922.893-72',
        data_conversao_iso: '',
        data_conversao_texto: '00/00/0000',
        data_batismo_iso: '2018-07-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Raimundo Fontele Gomes',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 109
      {
        numero_ficha: '109',
        nome: 'Joaquim Fontenele Cardoso',
        filiacao: 'Manoel Chaves Cardoso e Maria Stela Fontenele Cardoso',
        data_nascimento_iso: '1971-10-15 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casado',
        rg: '2429330-92',
        cpf: '012.075.703-62',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '1987-06-27 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Presbítero',
      },
      // MEMBRO Nº 110
      {
        numero_ficha: '110',
        nome: 'Maria da Conceição Costa Cardoso',
        filiacao: 'Francisco Viana da Costa e Maria do Carmo Fontenele Cardoso',
        data_nascimento_iso: '1975-09-15 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casada',
        rg: '2007073008-8',
        cpf: '012.599.223-83',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '1988-10-11 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 111
      {
        numero_ficha: '111',
        nome: 'Vitória Costa Cardoso',
        filiacao: 'Joaquim Fontenele Cardoso e Maria da Conceição Costa Cardoso',
        data_nascimento_iso: '2006-08-25 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – Ce',
        estado_civil: 'Solteira',
        rg: '00000000000',
        cpf: '113.390.773-37',
        data_conversao_iso: '',
        data_conversao_texto: 'Nasceu na fé',
        data_batismo_iso: '2020-11-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 112
      {
        numero_ficha: '112',
        nome: 'Gilson Fontenele Cardozo',
        filiacao: 'Manoel Chaves Cardozo e Maria Stela Fontenele',
        data_nascimento_iso: '1969-12-03 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca– Ce',
        estado_civil: 'Casado',
        rg: '1633786-88',
        cpf: '002.530.803-39',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '1987-02-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Presbítero',
      },
      // MEMBRO Nº 113
      {
        numero_ficha: '113',
        nome: 'Antônia de Carvalho Ferreira Cardoso (Elizete)',
        filiacao: 'José Alves Ferreira e Raimunda Ferreira de Carvalho',
        data_nascimento_iso: '1975-10-26 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca– Ce',
        estado_civil: 'Casada',
        rg: '2429333-92',
        cpf: '024.483.013-44',
        data_conversao_iso: '1989-10-07 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '1990-02-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 114
      {
        numero_ficha: '114',
        nome: 'Antonio Carlos Rodrigues de Matos',
        filiacao: 'Antônio Pereira de Matos e Isaura Rodrigues de Matos',
        data_nascimento_iso: '1997-01-16 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Solteiro',
        rg: '00000000000',
        cpf: '063.445.983-01',
        data_conversao_iso: '2017-05-14 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 115
      {
        numero_ficha: '115',
        nome: 'Aucinei Rodrigues de Matos',
        filiacao: 'Antônio Pereira de Matos e Isaura Rodrigues de Matos',
        data_nascimento_iso: '1998-06-19 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – Ce',
        estado_civil: 'Solteiro',
        rg: '2008649650-0',
        cpf: '072.280.713-95',
        data_conversao_iso: '2017-05-08 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 116
      {
        numero_ficha: '116',
        nome: 'Luciene Rodrigues de Matos',
        filiacao: 'Antônio Pereira de Matos e Isaura Rodrigues de Matos',
        data_nascimento_iso: '2000-11-22 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Solteira',
        rg: '000000000-0',
        cpf: '082.909.303-64',
        data_conversao_iso: '2017-06-02 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 117
      {
        numero_ficha: '117',
        nome: 'Luziene Rodrigues de Matos',
        filiacao: 'Antônio Pereira de Matos e Isaura Rodrigues de Matos',
        data_nascimento_iso: '2002-07-26 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Solteira',
        rg: '000000000-0',
        cpf: '093.338.283-97',
        data_conversao_iso: '2017-05-08 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 118
      {
        numero_ficha: '118',
        nome: 'Letícia Rodrigues de Matos',
        filiacao: 'Antônio Pereira de Matos e Isaura Rodrigues de Matos',
        data_nascimento_iso: '2008-04-22 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – Ce',
        estado_civil: 'Solteira',
        rg: '000000000-0',
        cpf: '128.686.943-90',
        data_conversao_iso: '2021-04-11 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2021-10-03 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 119
      {
        numero_ficha: '119',
        nome: 'Maria Aparecida de Oliveira Sampaio',
        filiacao: 'Francisco Domingos de Oliveira e Francisca Almeida de Oliveira',
        data_nascimento_iso: '1963-04-30 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Divorciada',
        rg: '2008519505-1',
        cpf: '',
        data_conversao_iso: '2009-02-02 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2009-03-29 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Raimundo Belchior',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 120
      {
        numero_ficha: '120',
        nome: 'Joana Paula da Silva Alves',
        filiacao: 'Raimundo Alves da Silva e Maria do Socorro da Silva',
        data_nascimento_iso: '1983-10-15 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Martinopole – Ce',
        estado_civil: 'Casada',
        rg: '2002031046638',
        cpf: '007.715.413-41',
        data_conversao_iso: '2018-03-28 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2018-07-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Raimundo Fontele Gomes',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 121
      {
        numero_ficha: '121',
        nome: 'José Sampaio Fontenele',
        filiacao: 'Auriverdes Fontenele de Assis Filho e Francinete Lopes Sampaio Fontenele',
        data_nascimento_iso: '2002-10-02 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – Ce',
        estado_civil: 'Solteiro',
        rg: '00000000000',
        cpf: '090.520.943-57',
        data_conversao_iso: '2021-07-25 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2021-10-03 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Argentina B. Fernandes',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 122
      {
        numero_ficha: '122',
        nome: 'João Gustavo Sampaio Fontenele',
        filiacao: 'Auriverdes Fontenele de Assis Filho e Francinete Lopes Sampaio Fontenele',
        data_nascimento_iso: '2008-01-11 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Solteiro',
        rg: '00000000000',
        cpf: '091.467.483-85',
        data_conversao_iso: '2021-07-25 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2021-10-03 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Argentina B. Fernandes',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 123
      {
        numero_ficha: '123',
        nome: 'Sandra Rodrigues Dias',
        filiacao: 'Vicente Rodrigues Dias e Antônia Lopes de Sousa',
        data_nascimento_iso: '1989-06-17 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Solteira',
        rg: '2007202897-6',
        cpf: '058.487.323-96',
        data_conversao_iso: '2005-09-06 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2005-10-31 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Francisco Gualberto da Cunha',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 124
      {
        numero_ficha: '124',
        nome: 'Francisco Alves de Menezes Júnior',
        filiacao: 'Francisco Alves de Menezes e Maria Oliveira de Menezes',
        data_nascimento_iso: '1994-06-25 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – Ce',
        estado_civil: 'Casado',
        rg: '2007683141-2',
        cpf: '063.252.063-98',
        data_conversao_iso: '2011-06-23 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2012-05-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. Alberto Batista Fontenele',
        observacao: 'Função: Diácono',
      },
      // MEMBRO Nº 125
      {
        numero_ficha: '125',
        nome: 'Virgilany Oliveira Aguiar',
        filiacao: 'Francisco de Assis Oliveira e Lúcia Maria Aguiar',
        data_nascimento_iso: '1997-04-06 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – Ce',
        estado_civil: 'Casado',
        rg: '2008649669-1',
        cpf: '072.150.563-50',
        data_conversao_iso: '2011-06-23 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2012-05-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. Alberto Batista Fontenele',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 126
      {
        numero_ficha: '126',
        nome: 'Fernando Rocha',
        filiacao: 'Valdemar Raimundo da Rocha e Francisca das Chagas Rocha',
        data_nascimento_iso: '1986-03-03 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Massapê-Ce',
        estado_civil: 'Casado',
        rg: '2006031015832',
        cpf: '037.142.703-70',
        data_conversao_iso: '2016-08-15 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alberto Batista Fontenele',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 127
      {
        numero_ficha: '127',
        nome: 'Antônia Cardoso da Costa',
        filiacao: 'Benedito Cardoso Gomes e Joaquina Ribeiro de Souza',
        data_nascimento_iso: '1962-08-11 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – Ce',
        estado_civil: 'Casada',
        rg: '1547398-88',
        cpf: '703.023.593-20',
        data_conversao_iso: '',
        data_conversao_texto: '20/09/2007 Ap.',
        data_batismo_iso: '2008-03-16 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Antônio Ferreira Gomes',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 128
      {
        numero_ficha: '128',
        nome: 'Ernando Fontenele Sampaio',
        filiacao: 'José de Sousa Sampaio e Francisca Fontenele Araújo',
        data_nascimento_iso: '1996-05-05 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – Ce',
        estado_civil: 'Solteiro',
        rg: '2008362221-1',
        cpf: '069.157.153-80',
        data_conversao_iso: '2015-11-02 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2016-05-22 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Saco',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 129
      {
        numero_ficha: '129',
        nome: 'Kleidson Régis Frota Veras',
        filiacao: 'Ireudo Frota Veras e Anastácia Frota de Araújo Veras',
        data_nascimento_iso: '1981-02-28 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral - Ce',
        estado_civil: 'Casado',
        rg: '98031066004',
        cpf: '884.637.703-63',
        data_conversao_iso: '2009-03-15 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2011-01-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. Alberto Batista Fontenele',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 130
      {
        numero_ficha: '130',
        nome: 'Priscila Pessoa de Sousa Frota',
        filiacao: 'Lourenço Justiniano de Sousa Neto e Terezinha Pessoa Souza',
        data_nascimento_iso: '1990-03-06 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – Ce',
        estado_civil: 'Casada',
        rg: '2005098079826',
        cpf: '053.122.533-08',
        data_conversao_iso: '2009-03-15 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2011-01-08 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Av. Alberto Batista Fontenele',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 131
      {
        numero_ficha: '131',
        nome: 'Raimundo de Almeida dos Santos',
        filiacao: 'Francisco Antonio dos Santos e Antonia de Almeida Sobrinho',
        data_nascimento_iso: '1973-01-21 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Granja – Ce',
        estado_civil: 'Casado',
        rg: '91005017215',
        cpf: '000.301.403-74',
        data_conversao_iso: '',
        data_conversao_texto: '00/00/0000',
        data_batismo_iso: '2020-11-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Jacinta Marques de Assis',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 132
      {
        numero_ficha: '132',
        nome: 'Maria das Graças da Costa Moreira (Maria Moreira)',
        filiacao: 'Manoel Fernandes Moreira e Eurides da Costa Moreira',
        data_nascimento_iso: '1980-06-02 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Tocantinopole – Go',
        estado_civil: 'Casada',
        rg: '3065740-96',
        cpf: '888.285.063-34',
        data_conversao_iso: '1994-02-05 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '1994-06-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Jacinta Marques de Assis',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 133
      {
        numero_ficha: '133',
        nome: 'Manoel Sousa Sampaio',
        filiacao: 'Antônio Eudes Sampaio e Rosa Clemente de Sousa',
        data_nascimento_iso: '1998-09-09 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Casado',
        rg: '',
        cpf: '',
        data_conversao_iso: '2017-09-08 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: '',
      },
      // MEMBRO Nº 134
      {
        numero_ficha: '134',
        nome: 'Elinaia Ferreira Cardoso',
        filiacao: 'Gilson Fontenele Cardoso e Antônia Carvalho Ferreira Cardoso',
        data_nascimento_iso: '1997-03-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – Ce',
        estado_civil: 'Casada',
        rg: '',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: 'Na fé',
        data_batismo_iso: '2010-01-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alto',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 135
      {
        numero_ficha: '135',
        nome: 'Regilânia Oliveira Aguiar',
        filiacao: 'Francisco de Assis Oliveira e Lucia Maria Aguiar',
        data_nascimento_iso: '1988-02-01 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – CE',
        estado_civil: 'Casada',
        rg: '',
        cpf: '',
        data_conversao_iso: '2016-10-18 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alberto Batista Fontenele',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 137 (ficha 136 pula / sem registro na 136)
      {
        numero_ficha: '137',
        nome: 'Ernanda Fontenele Sampaio',
        filiacao: 'José de Sousa Sampaio e Francisca Fontenele Araújo',
        data_nascimento_iso: '1999-01-25 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Solteira',
        rg: '2015040285 - 0',
        cpf: '079.026.853-13',
        data_conversao_iso: '2017-03-27 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Saco',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 138
      {
        numero_ficha: '138',
        nome: 'Gabriel Régis Pessoa Frota',
        filiacao: 'Kleidson Régis Frota Véras e Priscila Pessoa de Sousa Frota',
        data_nascimento_iso: '2009-12-22 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteiro',
        rg: '2019170955 - 1',
        cpf: '123.903.403 - 26',
        data_conversao_iso: '2019-03-15 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Alberto Batista Fontenele',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 139
      {
        numero_ficha: '139',
        nome: 'Felizardo Menezes Magalhães',
        filiacao: 'Antonio Carneiro Magalhães e Antonia Felizarda Menezes Magalhães',
        data_nascimento_iso: '2007-06-05 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteiro',
        rg: '000000000000',
        cpf: '118.415.903 - 39',
        data_conversao_iso: '2023-07-02 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinha - Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 140
      {
        numero_ficha: '140',
        nome: 'Bruno Menezes Magalhães',
        filiacao: 'Antonio Carneiro Magalhães e Antonia Felizarda Menezes Magalhães',
        data_nascimento_iso: '2009-08-18 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteiro',
        rg: '000000000000',
        cpf: '118.415.573 - 90',
        data_conversao_iso: '2023-07-02 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinha - Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 141
      {
        numero_ficha: '141',
        nome: 'Davi Lucas Menezes Leopoldo',
        filiacao: 'Denevaldo Leopoldo do Nascimento e Michely Menezes de Oliveira',
        data_nascimento_iso: '2010-11-29 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteiro',
        rg: '000000000000',
        cpf: '099.968.173-77',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 142
      {
        numero_ficha: '142',
        nome: 'Francisco Alves de Meneses',
        filiacao: 'Vicente Alves de Meneses e Francisca Martins dos Santos',
        data_nascimento_iso: '1965-08-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Casado',
        rg: '2015200893 - 9',
        cpf: '038.340.443 - 69',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 143
      {
        numero_ficha: '143',
        nome: 'Nadilkson Fagney da Rocha Monteiro',
        filiacao: 'Nadir Ferreira Monteiro e Maria de Fatima da Rocha Monteiro',
        data_nascimento_iso: '1989-10-30 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'STA Isabel do Pará – PA',
        estado_civil: 'Casado',
        rg: '5897089',
        cpf: '988.864.872-15',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2002-04-21 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Auxiliar',
      },
      // MEMBRO Nº 144
      {
        numero_ficha: '144',
        nome: 'João Kaio Silva Chaves',
        filiacao: 'Kelson Cunha Chaves e Antonia Daniele Silva Matos',
        data_nascimento_iso: '2004-07-11 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo - CE',
        estado_civil: 'Solteiro',
        rg: '20220379542',
        cpf: '026.390.603-50',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2017-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 145
      {
        numero_ficha: '145',
        nome: 'José Alves Ferreira Filho',
        filiacao: 'José Alves Ferreira e Raimunda Ferreira de Carvalho',
        data_nascimento_iso: '1985-04-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Coreaú – Ce',
        estado_civil: 'Casado',
        rg: '2004015093780',
        cpf: '025.590.063-59',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '1999-05-15 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinhas',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 146
      {
        numero_ficha: '146',
        nome: 'Maria Amanda Sampaio Alves',
        filiacao: 'Valfrido Laurindo de Sampaio e Maria do Socorro Sampaio',
        data_nascimento_iso: '1990-09-16 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca - Ce',
        estado_civil: 'Casada',
        rg: '2007015053103',
        cpf: '040.735.283-00',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '',
        data_batismo_texto: '18/10/2004 Aprox.',
        endereco: 'Casinhas',
        observacao: '',
      },
      // MEMBRO Nº 147
      {
        numero_ficha: '147',
        nome: 'Vitória Sampaio Alves',
        filiacao: 'José Alves Ferreira Filho e Maria Amanda Sampaio Alves',
        data_nascimento_iso: '2009-09-07 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral - Ce',
        estado_civil: 'Solteira',
        rg: '0000000000',
        cpf: '638.480.263-50',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinhas',
        observacao: '',
      },
      // MEMBRO Nº 148
      {
        numero_ficha: '148',
        nome: 'Joais Sampaio Alves',
        filiacao: 'José Alves Ferreira Filho e Maria Amanda Sampaio Alves',
        data_nascimento_iso: '2006-12-30 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral - Ce',
        estado_civil: 'Solteiro',
        rg: '0000000000',
        cpf: '122.166.553-76',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Casinhas',
        observacao: '',
      },
      // MEMBRO Nº 149
      {
        numero_ficha: '149',
        nome: 'Maiara Rodrigues de Vasconcelos',
        filiacao: 'Evandro Rodrigues de Souza e Maria José Martins de Vasconcelos Souza',
        data_nascimento_iso: '2009-10-12 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral - Ce',
        estado_civil: 'Solteira',
        rg: '0000000000',
        cpf: '638.485.833-99',
        data_conversao_iso: '2016-01-15 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: '',
      },
      // MEMBRO Nº 150
      {
        numero_ficha: '150',
        nome: 'Antonia Grigório de Sampaio Mato',
        filiacao: 'Raimundo Grigório de Sampaio e Joaquina Ferreira de Souza',
        data_nascimento_iso: '1967-03-03 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Casada',
        rg: '2007083443 - 6',
        cpf: '796.504.493 - 53',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 151
      {
        numero_ficha: '151',
        nome: 'Maria Aurélia de Almeida Matos',
        filiacao: 'Raimundo Fernandes de Almeida e Tereza Rodrigues de Almeida',
        data_nascimento_iso: '1985-01-29 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Casada',
        rg: '0000000000 - 0',
        cpf: '015.282.262 - 13',
        data_conversao_iso: '2017-04-02 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-06-10 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 152
      {
        numero_ficha: '152',
        nome: 'Maria da Conceição Viturino da Costa',
        filiacao: 'Paulo Fontenele da Costa e Ana Cardoso Viturino da Costa',
        data_nascimento_iso: '2008-03-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Solteira',
        rg: '0000000000 - 0',
        cpf: '119.103.453-42',
        data_conversao_iso: '2018-06-18 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 153
      {
        numero_ficha: '153',
        nome: 'Ruth Laurindo de Sampaio',
        filiacao: 'Valfrido Laurindo de Sampaio e Maria do Socorro Sampaio',
        data_nascimento_iso: '2005-11-12 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Solteira',
        rg: '0000000000 - 0',
        cpf: '109.350.183-95',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2020-11-14 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: '',
      },
      // MEMBRO Nº 154
      {
        numero_ficha: '154',
        nome: 'Maria Félix da Cunha',
        filiacao: 'Antônio Félix da Cunha e Raimunda Helena da Cunha',
        data_nascimento_iso: '1970-12-17 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Casada',
        rg: '',
        cpf: '835.622.063-72',
        data_conversao_iso: '',
        data_conversao_texto: '00/00/0000',
        data_batismo_iso: '2010-08-21 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Avenida: Alberto Batista Fontenele',
        observacao: '',
      },
      // MEMBRO Nº 155
      {
        numero_ficha: '155',
        nome: 'Josué Rodrigues Matos',
        filiacao: 'Luiz Feijão de Matos e Terezinha de Jesus Rodrigues Matos',
        data_nascimento_iso: '2004-04-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Forquilha - CE',
        estado_civil: 'Solteiro',
        rg: '000000000',
        cpf: '621.828.803-05',
        data_conversao_iso: '2014-08-14 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2017-02-11 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 156
      {
        numero_ficha: '156',
        nome: 'Alice Moreira de Vasconcelos',
        filiacao: 'Belchior Fernandes de Vasconcelos e Ernestina Moreira Vasconcelos',
        data_nascimento_iso: '1996-12-10 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – CE',
        estado_civil: 'Casada',
        rg: '',
        cpf: '072.338.673-05',
        data_conversao_iso: '',
        data_conversao_texto: 'Na fé',
        data_batismo_iso: '2010-07-04 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Rua Francisco Gualberto da Cunha',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 157
      {
        numero_ficha: '157',
        nome: 'Iranilda Cardoso Eugenio',
        filiacao: 'Juvenal Eugenio Carneiro e Maria de Fatíma Ancelmo Cardoso',
        data_nascimento_iso: '2002-05-01 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Solteira',
        rg: '2018157003 - 8',
        cpf: '091.020.623 - 64',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '2023-12-09 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 158
      {
        numero_ficha: '158',
        nome: 'Antonia Queren Hapuquec Fernandes',
        filiacao: 'José Rejanio da Costa e Antonia Cristiane Cesar Fernandes',
        data_nascimento_iso: '2011-05-21 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteira',
        rg: '000000000 - 0',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: 'Não lembra',
        data_batismo_iso: '',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 159
      {
        numero_ficha: '159',
        nome: 'Talyta Batista Vasconcelos',
        filiacao: 'Antônio de Vasconcelos e Maria Lindalva Vasconcelos Batista',
        data_nascimento_iso: '2010-08-16 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteira',
        rg: '',
        cpf: '116.331.463-32',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 160
      {
        numero_ficha: '160',
        nome: 'Anderley Vasconcelos de Matos',
        filiacao: 'Francisco Abelardo Rodrigues de Matos e Andreane Martins de Vasconcelos Matos',
        data_nascimento_iso: '2011-12-06 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteiro',
        rg: '2022222052-4',
        cpf: '116.591.173-64',
        data_conversao_iso: '2016-09-06 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: '',
      },
      // MEMBRO Nº 161
      {
        numero_ficha: '161',
        nome: 'Samuel Freire Carneiro',
        filiacao: 'Valderlanio Carneiro Araújo e Joana Freire Carneiro',
        data_nascimento_iso: '2013-06-13 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteiro',
        rg: '2019089471-1',
        cpf: '105.127.043-09',
        data_conversao_iso: '2018-05-12 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 162
      {
        numero_ficha: '162',
        nome: 'Antonio Nonato de Souza Neto',
        filiacao: 'Jaílson Carvalho de Souza e Maiana Alves Teixeira',
        data_nascimento_iso: '2013-05-29 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteiro',
        rg: '',
        cpf: '131.468.223-77',
        data_conversao_iso: '2023-07-07 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 163
      {
        numero_ficha: '163',
        nome: 'Ana Hevellen Fernandes Ferreira',
        filiacao: 'Valderlan Carvalho Ferreira e Natalina Fernandes de Souza',
        data_nascimento_iso: '2013-03-30 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteira',
        rg: '',
        cpf: '077.469.793-86',
        data_conversao_iso: '2019-10-07 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 164
      {
        numero_ficha: '164',
        nome: 'Tatiana Martins de Menezes',
        filiacao: 'Elisa Martins de Menezes',
        data_nascimento_iso: '1979-03-04 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Tianguá – CE',
        estado_civil: 'Casada',
        rg: '2008824745 - 1',
        cpf: '000.538.463-83',
        data_conversao_iso: '2017-08-27 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 165
      {
        numero_ficha: '165',
        nome: 'Ana Paula Viturino da Costa',
        filiacao: 'Paulo Fontenele da Costa e Ana Cardoso Viturino da Costa',
        data_nascimento_iso: '2013-01-21 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral– CE',
        estado_civil: 'Solteira',
        rg: '2019170947-0',
        cpf: '119.104.063-17',
        data_conversao_iso: '',
        data_conversao_texto: '00/03/2016',
        data_batismo_iso: '2025-06-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 166
      {
        numero_ficha: '166',
        nome: 'Joélia Costa Cardozo',
        filiacao: 'Joel Costa Cardozo e Noélia Costa do Nascimento Cardozo',
        data_nascimento_iso: '2011-05-21 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Moraújo – CE',
        estado_civil: 'Solteira',
        rg: '',
        cpf: '113.389.273-61',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 167
      {
        numero_ficha: '167',
        nome: 'Antonio Sampaio Rodrigues',
        filiacao: '',
        data_nascimento_iso: '',
        data_nascimento_texto: '00/00/0000',
        naturalidade: '',
        estado_civil: 'Solteiro',
        rg: '',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-06-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 168
      {
        numero_ficha: '168',
        nome: 'Laís Pereira Dourado',
        filiacao: 'João Paulo Ferreira Dourado e Edmaura Pereira Rodrigues Dourado',
        data_nascimento_iso: '',
        data_nascimento_texto: '00/00/0000',
        naturalidade: '',
        estado_civil: 'Solteira',
        rg: '',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-06-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 169
      {
        numero_ficha: '169',
        nome: 'Antônia Pereira de Matos Sampaio',
        filiacao: '',
        data_nascimento_iso: '',
        data_nascimento_texto: '00/00/0000',
        naturalidade: '',
        estado_civil: 'Casada',
        rg: '',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 170
      {
        numero_ficha: '170',
        nome: 'Isaque Fernandes Frota',
        filiacao: 'José Rodrigo Frota e Jaqueline Fernandes Cavalcante Frota',
        data_nascimento_iso: '',
        data_nascimento_texto: '00/00/0000',
        naturalidade: '',
        estado_civil: 'Solteiro',
        rg: '',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-06-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 171
      {
        numero_ficha: '171',
        nome: 'Samuel Lucas Oliveira Santiago',
        filiacao: 'Francisco Farias Santiago e Gaspar Oliveira Farias',
        data_nascimento_iso: '',
        data_nascimento_texto: '00/00/0000',
        naturalidade: '',
        estado_civil: 'Solteiro',
        rg: '',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-06-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 172
      {
        numero_ficha: '172',
        nome: 'Renata Hellen Rodrigues Sampaio',
        filiacao: '',
        data_nascimento_iso: '',
        data_nascimento_texto: '00/00/0000',
        naturalidade: '',
        estado_civil: 'Solteira',
        rg: '',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 173
      {
        numero_ficha: '173',
        nome: 'Raí Ferreira de Matos',
        filiacao: '',
        data_nascimento_iso: '',
        data_nascimento_texto: '',
        naturalidade: '',
        estado_civil: 'Casado',
        rg: '',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-07-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 174
      {
        numero_ficha: '174',
        nome: 'Raí de Sousa Frota',
        filiacao: '',
        data_nascimento_iso: '',
        data_nascimento_texto: '00/00/0000',
        naturalidade: '',
        estado_civil: 'Solteiro',
        rg: '',
        cpf: '',
        data_conversao_iso: '',
        data_conversao_texto: '',
        data_batismo_iso: '2025-06-12 00:00:00.000Z',
        data_batismo_texto: '',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },

      // REGISTROS ESPECIAIS (Fichas 1 e 7)
      // MEMBRO Nº 1
      {
        numero_ficha: '1',
        nome: 'Antonio Levi Albuquerque Moreira',
        filiacao: 'Leandro Moreira Santos e Lucicleide Albuquerque Dourado Santos',
        data_nascimento_iso: '2011-06-12 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Uruoca – CE',
        estado_civil: 'Solteiro',
        rg: '2018163869 - 4',
        cpf: '111.678.683-40',
        data_conversao_iso: '2021-07-03 00:00:00.000Z',
        data_conversao_texto: '',
        data_batismo_iso: '',
        data_batismo_texto: '08/08/2026',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
      // MEMBRO Nº 7
      {
        numero_ficha: '7',
        nome: 'Gabriel Gleudson Fontenele Clemente',
        filiacao: 'Antonio Clemente do Nascimento e Antonia Sampaio Fontenele',
        data_nascimento_iso: '2005-05-08 00:00:00.000Z',
        data_nascimento_texto: '',
        naturalidade: 'Sobral – CE',
        estado_civil: 'Solteiro',
        rg: '',
        cpf: '073.065.032-43',
        data_conversao_iso: '',
        data_conversao_texto: '16/06/2026',
        data_batismo_iso: '',
        data_batismo_texto: '08/08/2026',
        endereco: 'Campanário',
        observacao: 'Função: Membro',
      },
    ]

    for (const m of membrosNovos) {
      let record
      // Idempotência: checagem prévia por numero_ficha
      try {
        record = app.findFirstRecordByData('membros', 'numero_ficha', m.numero_ficha)
      } catch (_) {
        record = new Record(colMembros)
      }

      record.set('numero_ficha', m.numero_ficha)
      record.set('nome', m.nome)
      record.set('filiacao', m.filiacao)
      record.set('naturalidade', m.naturalidade)
      record.set('estado_civil', m.estado_civil)
      record.set('rg', m.rg)
      record.set('cpf', m.cpf)
      record.set('endereco', m.endereco)
      record.set('observacao', m.observacao)
      record.set('congregacao', 'Sede')
      record.set('status', 'Ativo')

      if (m.data_nascimento_iso) {
        record.set('data_nascimento', m.data_nascimento_iso)
      } else {
        record.set('data_nascimento', null)
      }
      record.set('data_nascimento_texto', m.data_nascimento_texto)

      if (m.data_conversao_iso) {
        record.set('data_conversao', m.data_conversao_iso)
      } else {
        record.set('data_conversao', null)
      }
      record.set('data_conversao_texto', m.data_conversao_texto)

      if (m.data_batismo_iso) {
        record.set('data_batismo', m.data_batismo_iso)
      } else {
        record.set('data_batismo', null)
      }
      record.set('data_batismo_texto', m.data_batismo_texto)

      app.save(record)
    }
  },
  (app) => {
    // Reverter fichas 103..174 (exceto 136) e especiais 1 e 7
    const fichasReverter = ['1', '7']
    for (let f = 103; f <= 174; f++) {
      if (f !== 136) {
        fichasReverter.push(String(f))
      }
    }

    for (const f of fichasReverter) {
      try {
        const record = app.findFirstRecordByData('membros', 'numero_ficha', f)
        app.delete(record)
      } catch (_) {}
    }
  },
)
